openapi: 3.0.1
info:
  title: faasnap
  description: FaaSnap API
  version: 1.0.0
servers:
  - url: http://localhost:8080/
paths:
  /ui:
    get:
      description: UI
      responses:
        "200":
          description: ok
          content: { }
  /ui/data:
    get:
      description: UI
      responses:
        "200":
          description: ok
          content: { }
  /metrics:
    get:
      description: Metrics
      responses:
        "200":
          description: ok
          content: { }
  /functions:
    get:
      description: Return a list of functions
      responses:
        "200":
          description: List of functions
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Function'
                x-content-type: '*/*'
    post:
      description: Create a new function
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Function'
        required: false
      responses:
        "200":
          description: OK
          content: { }
        "400":
          description: Invalid request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/inline_response_400'
      x-codegen-request-body-name: function
  /vms:
    get:
      description: Returns a list of active VMs
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VM'
                x-content-type: '*/*'
    post:
      description: Create a new VM
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/vms_body'
        required: false
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/VM'
        "400":
          description: Invalid request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/inline_response_400'
      x-codegen-request-body-name: VM
  /vms/{vmId}:
    get:
      description: Describe a VM
      parameters:
        - name: vmId
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/VM'
        "400":
          description: Invalid request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/inline_response_400'
    delete:
      description: Stop a VM
      parameters:
        - name: vmId
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          content: { }
        "400":
          description: Invalid request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/inline_response_400'
  /vmms:
    post:
      description: Create a VMM in the pool
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/vmms_body'
        required: false
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/VM'
        "400":
          description: Invalid request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/inline_response_400'
      x-codegen-request-body-name: VMM
  /snapshots:
    put:
      description: Put snapshot (copy)
      parameters:
        - name: from_snapshot
          in: query
          required: true
          style: form
          explode: true
          schema:
            type: string
        - name: mem_file_path
          in: query
          required: true
          style: form
          explode: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Snapshot'
        "400":
          description: Invalid request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/inline_response_400'
    post:
      description: Take a snapshot
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Snapshot'
        required: false
      responses:
        "200":
          description: Success
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Snapshot'
        "400":
          description: Invalid request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/inline_response_400'
      x-codegen-request-body-name: snapshot
  /snapshots/{ssId}:
    post:
      description: Load a snapshot
      parameters:
        - name: ssId
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Invocation'
        required: false
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/VM'
        "400":
          description: Invalid request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/inline_response_400'
      x-codegen-request-body-name: invocation
    patch:
      description: Change snapshot state
      parameters:
        - name: ssId
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/snapshots_ssId_body'
        required: false
      responses:
        "200":
          description: OK
          content: { }
        "400":
          description: Invalid request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/inline_response_400'
      x-codegen-request-body-name: state
  /snapshots/{ssId}/mincore:
    get:
      description: Get mincore state
      parameters:
        - name: ssId
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "200":
          description: Mincore state
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "400":
          description: Invalid request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/inline_response_400'
    put:
      description: Put mincore state
      parameters:
        - name: ssId
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: source
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content: { }
        "400":
          description: Invalid request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/inline_response_400'
    post:
      description: Add mincore layer
      parameters:
        - name: ssId
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/ssId_mincore_body'
        required: true
      responses:
        "200":
          description: OK
          content: { }
        "400":
          description: Invalid request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/inline_response_400'
      x-codegen-request-body-name: layer
    patch:
      description: Change mincore state
      parameters:
        - name: ssId
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ssId_mincore_body_1'
        required: true
      responses:
        "200":
          description: OK
          content: { }
        "400":
          description: Invalid request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/inline_response_400'
      x-codegen-request-body-name: state
  /snapshots/{ssId}/reap:
    get:
      description: get reap state
      parameters:
        - name: ssId
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          content: { }
        "400":
          description: Invalid request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/inline_response_400'
    delete:
      description: delete reap state
      parameters:
        - name: ssId
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          content: { }
        "400":
          description: Invalid request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/inline_response_400'
    patch:
      description: Change reap state
      parameters:
        - name: ssId
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      requestBody:
        content:
          '*/*':
            schema:
              type: boolean
        required: false
      responses:
        "200":
          description: OK
          content: { }
        "400":
          description: Invalid request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/inline_response_400'
      x-codegen-request-body-name: cache
  /net-ifaces/{namespace}:
    put:
      description: Put a vm network
      parameters:
        - name: namespace
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/netifaces_namespace_body'
        required: false
      responses:
        "200":
          description: OK
          content: { }
        "400":
          description: Invalid request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/inline_response_400'
      x-codegen-request-body-name: interface
  /invocations:
    post:
      description: Post an invocation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Invocation'
        required: false
      responses:
        "200":
          description: Success
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
        "400":
          description: Invalid request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/inline_response_400'
      x-codegen-request-body-name: invocation
components:
  schemas:
    Function:
      required:
        - func_name
      type: object
      properties:
        func_name:
          type: string
        image:
          type: string
        kernel:
          type: string
        vcpu:
          type: integer
        mem_size:
          type: integer
      example:
        image: image
        vcpu: 0
        kernel: kernel
        mem_size: 6
        func_name: func_name
    VM:
      required:
        - vmId
      type: object
      properties:
        vmId:
          type: string
        state:
          type: string
        vmConf:
          type: object
          properties: { }
          example: { }
        vmPath:
          type: string
        pid:
          type: integer
        ip:
          type: string
      example:
        vmConf: { }
        vmId: vmId
        ip: ip
        pid: 0
        state: state
        vmPath: vmPath
    Snapshot:
      required:
        - vmId
      type: object
      properties:
        vmId:
          type: string
        ssId:
          type: string
        snapshot_type:
          type: string
        snapshot_path:
          type: string
        mem_file_path:
          type: string
        version:
          type: string
        record_regions:
          type: boolean
        size_threshold:
          type: integer
        interval_threshold:
          type: integer
      example:
        interval_threshold: 6
        mem_file_path: mem_file_path
        vmId: vmId
        snapshot_path: snapshot_path
        size_threshold: 0
        snapshot_type: snapshot_type
        record_regions: true
        version: version
        ssId: ssId
    Invocation:
      required:
        - func_name
      type: object
      properties:
        func_name:
          type: string
        vmId:
          type: string
        ssId:
          type: string
        params:
          type: string
        mincore:
          type: integer
        mincore_size:
          type: integer
        loadMincore:
          type: array
          items:
            type: integer
        use_mem_file:
          type: boolean
        overlay_regions:
          type: boolean
        use_ws_file:
          type: boolean
        vmm_load_ws:
          type: boolean
        enableReap:
          type: boolean
        wsFileDirectIo:
          type: boolean
        wsSingleRead:
          type: boolean
        namespace:
          type: string
    inline_response_400:
      type: object
      properties:
        message:
          type: string
    vms_body:
      type: object
      properties:
        func_name:
          type: string
        ssId:
          type: string
        namespace:
          type: string
    vmms_body:
      type: object
      properties:
        namespace:
          type: string
        enableReap:
          type: boolean
    snapshots_ssId_body:
      type: object
      properties:
        dig_hole:
          type: boolean
        load_cache:
          type: boolean
        drop_cache:
          type: boolean
    inline_response_200:
      type: object
      properties:
        nlayers:
          type: integer
        n_nz_regions:
          type: integer
        nz_region_size:
          type: integer
        n_ws_regions:
          type: integer
        ws_region_size:
          type: integer
      example:
        nz_region_size: 1
        n_nz_regions: 6
        ws_region_size: 5
        nlayers: 0
        n_ws_regions: 5
    ssId_mincore_body:
      type: object
      properties:
        position:
          type: integer
        fromDiff:
          type: string
    ssId_mincore_body_1:
      type: object
      properties:
        from_records_size:
          type: integer
        trim_regions:
          type: boolean
        to_ws_file:
          type: string
        inactive_ws:
          type: boolean
        zero_ws:
          type: boolean
        size_threshold:
          type: integer
        interval_threshold:
          type: integer
        mincore_cache:
          type: array
          items:
            type: integer
        drop_ws_cache:
          type: boolean
    netifaces_namespace_body:
      type: object
      properties:
        host_dev_name:
          type: string
        iface_id:
          type: string
        guest_mac:
          type: string
        guest_addr:
          type: string
        unique_addr:
          type: string
    inline_response_200_1:
      type: object
      properties:
        duration:
          type: number
        result:
          type: string
        vmId:
          type: string
        traceId:
          type: string
      example:
        duration: 0.8008281904610115
        result: result
        traceId: traceId
        vmId: vmId
  responses:
    "400Error":
      description: Invalid request
      content:
        '*/*':
          schema:
            type: object
            properties:
              message:
                type: string
x-original-swagger-version: "2.0"
